import React from "react";
import { ViewStyle } from "react-native";
import {
    // tabs & common
    LayoutDashboard,
    LayoutGrid,
    Car,
    ClipboardList,
    Building2,
    User,
    HelpCircle,
    // actions/status
    RefreshCw,
    CloudCheck,
    CheckCircle2,
    AlertCircle,
    CirclePlus,
    CalendarDays,
    ChevronRight,
    ChevronLeft,
    ChevronDown,
    Database,
    Info,
    BarChart3,
    Check,
    Plus,
    TreePalm,
    Shield,
    ShieldCheck,
    LogOut,
    UserCircle,
    Wind,
    ClipboardPlus,
    Filter,
    X,
    Search,
    Phone,
    Cloud,
    Clock,
    FileText,
    DollarSign,
    Cigarette,
    Receipt,
    FileType,
    Banknote,
    Calendar,
    MapPin,
    SearchX,
    Edit,
    Trash2,
    Bot,
    MessageCircle,
    Send,
    Minimize2,
    Maximize2,
    Eye,
    EyeOff,
    Lock,
    Bell,
    Settings,
    Fuel,
    CircleDot,
    Camera,
    Hash,
    XCircle,
    Save,
    Mail,
    CameraOff,
    SwitchCamera,
    Hourglass,
} from "lucide-react-native";

const ICONS = {
    LayoutDashboard,
    LayoutGrid,
    Car,
    ClipboardList,
    Building2,
    User,
    HelpCircle,
    RefreshCw,
    CloudCheck,
    CheckCircle2,
    AlertCircle,
    CirclePlus,
    CalendarDays,
    ChevronRight,
    ChevronLeft,
    ChevronDown,
    Database,
    Info,
    BarChart3,
    Check,
    Plus,
    TreePalm,
    Shield,
    ShieldCheck,
    LogOut,
    UserCircle,
    Wind,
    ClipboardPlus,
    Filter,
    X,
    Search,
    Phone,
    Cloud,
    Clock,
    FileText,
    DollarSign,
    Cigarette,
    Receipt,
    FileType,
    Banknote,
    Calendar,
    MapPin,
    SearchX,
    Edit,
    Trash2,
    Bot,
    MessageCircle,
    Send,
    Minimize2,
    Maximize2,
    Eye,
    EyeOff,
    Lock,
    Bell,
    Settings,
    Fuel,
    CircleDot,
    Camera,
    Hash,
    XCircle,
    Save,
    Mail,
    CameraOff,
    SwitchCamera,
    Hourglass,
    CheckCircle: CheckCircle2, // Alias
} as const;

// Supported icon names mapping from existing MaterialIcons names to Lucide icons
const nameMap: Record<string, keyof typeof ICONS> = {
    // tabs
    dashboard: "LayoutDashboard",
    "directions-car": "Car",
    assignment: "ClipboardList",
    business: "Building2",
    person: "User",
    help: "HelpCircle",

    // common
    sync: "RefreshCw",
    "cloud-done": "CloudCheck",
    "check-circle": "CheckCircle2",
    "alert-circle": "AlertCircle",
    "add-circle": "CirclePlus",
    event: "CalendarDays",
    "chevron-right": "ChevronRight",
    storage: "Database",
    info: "Info",
    help_outline: "HelpCircle",
    "bar-chart": "BarChart3",
    check: "Check",
    plus: "Plus",
    car: "Car",
    tree: "TreePalm",
    shield: "Shield",
    "shield-check": "ShieldCheck",
    "view-dashboard": "LayoutDashboard",
    logout: "LogOut",
    "account-circle": "UserCircle",
    "weather-windy": "Wind",
    air: "Cloud",
    park: "TreePalm",
    "clipboard-text": "FileText",
    "clock-outline": "Clock",
    "currency-php": "Banknote",
    "smoke-detector": "Cigarette",
    receipt: "Receipt",
    "file-document-outline": "FileType",
    "currency-usd": "Banknote",
    calendar: "Calendar",
    "map-marker": "MapPin",
    "search-off": "SearchX",
    "receipt-outline": "Receipt",
    "currency-usd-off": "X",
    // edit and delete icons
    pencil: "Edit",
    delete: "Trash2",
    // password visibility
    eye: "Eye",
    "eye-off": "EyeOff",
    // chatbot icons
    bot: "Bot",
    // material 'psychology' used in ChatbotModal -> map to bot
    psychology: "Bot",
    // alias used by some components / Paper FABs
    robot: "Bot",
    "message-circle": "MessageCircle",
    send: "Send",
    "minimize-2": "Minimize2",
    "maximize-2": "Maximize2",
    // extras used by code
    "assignment-add": "ClipboardPlus",
    filter: "Filter",
    "filter-variant": "Filter",
    search: "Search",
    magnify: "Search",
    close: "X",
    phone: "Phone",
    lock: "Lock",
    "lock-outline": "Lock",
    bell: "Bell",
    "bell-outline": "Bell",
    settings: "Settings",
    "settings-outline": "Settings",
    // camera icons
    "camera-off": "CameraOff",
    camera: "Camera",
    "flip-camera-ios": "SwitchCamera",
    "switch-camera": "SwitchCamera",
    "hourglass-empty": "Hourglass",
};

export type IconName = keyof typeof nameMap | keyof typeof ICONS;

export interface IconProps {
    name: IconName;
    size?: number;
    color?: string;
    style?: ViewStyle;
}

export default function Icon({ name, size = 24, color = "#000", style }: IconProps) {
    // Allow direct Lucide names too
    const lucideName = (nameMap[name as string] || (name as keyof typeof ICONS)) as keyof typeof ICONS;
    const LucideIcon = ICONS[lucideName] as unknown as React.ComponentType<any>;

    if (!LucideIcon) {
        const Fallback = HelpCircle as any;
        return <Fallback size={size} color={color} style={style} />;
    }

    return <LucideIcon size={size} color={color} style={style} />;
}
