import React, { useState } from "react";
import { Input } from "@/presentation/components/shared/ui/input";
import { Label } from "@/presentation/components/shared/ui/label";
import { Button } from "@/presentation/components/shared/ui/button";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/presentation/components/shared/ui/select";
import { toast } from "sonner";

interface FeeRecordFormProps {
    mode: "add" | "edit" | "view";
    initialData?: any;
    onSave: (data: any) => void;
    onCancel: () => void;
}

const FeeRecordForm: React.FC<FeeRecordFormProps> = ({
    mode,
    initialData,
    onSave,
    onCancel,
}) => {
    const [formData, setFormData] = useState({
        type: initialData?.type || "cutting_permit",
        amount: initialData?.amount || 0,
        payer_name: initialData?.payer_name || "",
        date: initialData?.date ? new Date(initialData.date) : new Date(),
        status: initialData?.status || "pending",
        or_number: initialData?.or_number || "",
        payment_date: initialData?.payment_date ? new Date(initialData.payment_date) : null,
    });

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();

        if (!formData.payer_name || formData.amount <= 0) {
            toast.error("Please fill in all required fields");
            return;
        }

        // Build payload
        const payload: any = {
            type: formData.type,
            amount: formData.amount,
            payer_name: formData.payer_name,
            date: formData.date.toISOString().split('T')[0],
            status: formData.status,
            or_number: formData.or_number || null,
            payment_date: formData.payment_date ? formData.payment_date.toISOString().split('T')[0] : null,
        };

        // Reference number will be auto-generated by database for new records

        onSave(payload);

        toast.success(mode === "add" ? "Fee record added successfully" : "Fee record updated successfully");
    };

    const isReadOnly = mode === "view";

    return (
        <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
                <div>
                    <Label htmlFor="type">Fee Type</Label>
                    <Select
                        value={formData.type}
                        onValueChange={(value) => setFormData({ ...formData, type: value })}
                        disabled={isReadOnly}
                    >
                        <SelectTrigger className="rounded-lg">
                            <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                            <SelectItem value="cutting_permit">Cutting Permit</SelectItem>
                            <SelectItem value="pruning_permit">Pruning Permit</SelectItem>
                            <SelectItem value="violation_fine">Violation Fine</SelectItem>
                        </SelectContent>
                    </Select>
                </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
                <div>
                    <Label htmlFor="payer_name">Payer Name *</Label>
                    <Input
                        id="payer_name"
                        value={formData.payer_name}
                        onChange={(e) => setFormData({ ...formData, payer_name: e.target.value })}
                        placeholder="Enter payer name"
                        disabled={isReadOnly}
                        className="rounded-lg"
                    />
                </div>
                <div>
                    <Label htmlFor="amount">Amount *</Label>
                    <Input
                        id="amount"
                        type="number"
                        min="0"
                        step="0.01"
                        value={formData.amount}
                        onChange={(e) => setFormData({ ...formData, amount: parseFloat(e.target.value) || 0 })}
                        placeholder="0.00"
                        disabled={isReadOnly}
                        className="rounded-lg"
                    />
                </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
                <div>
                    <Label htmlFor="date">Fee Date</Label>
                    <Input
                        type="date"
                        value={formData.date.toISOString().split('T')[0]}
                        onChange={(e) => setFormData({ ...formData, date: new Date(e.target.value) })}
                        disabled={isReadOnly}
                        className="rounded-lg"
                    />
                </div>
                <div>
                    <Label htmlFor="status">Status</Label>
                    <Select
                        value={formData.status}
                        onValueChange={(value) => setFormData({ ...formData, status: value })}
                        disabled={isReadOnly}
                    >
                        <SelectTrigger className="rounded-lg">
                            <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                            <SelectItem value="pending">Pending</SelectItem>
                            <SelectItem value="paid">Paid</SelectItem>
                            <SelectItem value="cancelled">Cancelled</SelectItem>
                        </SelectContent>
                    </Select>
                </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
                <div>
                    <Label htmlFor="or_number">OR Number</Label>
                    <Input
                        id="or_number"
                        value={formData.or_number}
                        onChange={(e) => setFormData({ ...formData, or_number: e.target.value })}
                        placeholder="Official Receipt Number"
                        disabled={isReadOnly}
                        className="rounded-lg"
                    />
                </div>
                {formData.status === "paid" && (
                    <div>
                        <Label htmlFor="payment_date">Payment Date</Label>
                        <Input
                            type="date"
                            value={formData.payment_date ? formData.payment_date.toISOString().split('T')[0] : ""}
                            onChange={(e) => setFormData({ ...formData, payment_date: e.target.value ? new Date(e.target.value) : null })}
                            disabled={isReadOnly}
                            className="rounded-lg"
                        />
                    </div>
                )}
            </div>

            {!isReadOnly && (
                <div className="flex justify-end gap-3 pt-4 border-t">
                    <Button type="button" variant="outline" onClick={onCancel} className="rounded-lg">
                        Cancel
                    </Button>
                    <Button type="submit" className="bg-[#0033a0] hover:bg-[#002a80] text-white rounded-lg">
                        {mode === "add" ? "Add Fee Record" : "Save Changes"}
                    </Button>
                </div>
            )}
        </form>
    );
};

export default FeeRecordForm;
