
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trjtbptzqqxmnydzknol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyanRicHR6cXF4bW55ZHprbm9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODg4ODksImV4cCI6MjA1OTI2NDg4OX0.kR20iawpyu-Nzh051bZ5iIWXYod69Mn-qbtdjRVFn5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
